title: "Zhechong\nHuang(黄柘铳)"
logo: /assets/logo.jpg
email: cudraniatrec@163.com
description: An undergraduate student majoring in conputer science at PKU
favicon: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

url: "zhechonghuang@github.io"

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: Résumé
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./assets/resume.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/ZhechongHuang

navigation:
  - name: Aboutme
    link: ./index.html
  - name: Education
    link: ./index.html#education
  - name: Teaching
    link: ./index.html#teaching
  - name: Publications
    link: ./index.html#publications
  - name: Awards
    link: ./index.html#awards